version: "3"

services:
  satellite_tasks_db:
    image: postgres:12.6
    container_name: satellite_tasks_db_container
    ports:
      - "54321:5432"
    environment:
      POSTGRES_DB: satellite_tasks_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    healthcheck:
      test: pg_isready -U myuser
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    environment:
      PYTHONUNBUFFERED: 1
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      satellite_tasks_db:
        condition: service_healthy
